### ISSUE TITLE
cant make yt2009 apks

### ISSUE THREAD

**Issue by Radiatorgaming420** [ftde0/yt2009#148]
basically i cant make any yt2009 apks due to registerDevice not existing, it dosent matter if i use autoapk.js or manually patch it, it still gives me the error "check system time and network" and mainly due to registerDevice not being in the yt2009 instance when hosted (im patching an apk for my own instance), i even double checked the apk instructions and i wasnt doing anything wrong as the instructions said to redirect "youtube.com/youtube/accounts/registerDevice" to "your" instance, in my case 192.168.0.107. Also ftde0, just wondering what exactly registerDevice is, thx.

**Comment by Radiatorgaming420** [comment]
bruhhhhhh

**Comment by Radiatorgaming420** [comment]
ok nvm i fixed the issue with registerdevice, i just redownloaded the repo, anyway, now the issue is "there was a problem starting up please check your network and system time" i dont know what the issue is (yt 2.4.4).

**Comment by ftde0** [comment]
you're probably messing up the registerDevice url within the apk itself, https/http? make sure the instance is reachable?

**Comment by Radiatorgaming420** [comment]
i mean, when i used the autoapk node, i just put "192.168.0.107" no http/https (nor a slash at the end)

**Comment by ftde0** [comment]
could you check that but making the apk manually? you say you've found registerDevice, but you're still getting an error related to registerDevice (system time check error on app start)

**Comment by Radiatorgaming420** [comment]
yeah, on site i checked like if registerdevice was even there, but then later on i found that it posts registerdevice, so i just left it as is, and after making the apk (i first tried autoapk then manually) i got the registerdevice error, i guess i could retry updating the apk, ill update you in a bit

**Comment by Radiatorgaming420** [comment]
ok just manually patched and recompiled, didnt seem to work
(still using yt 2.4.4)

**Comment by ftde0** [comment]
maybe try something like 2.3.4/2.1.6? if doesn't end up working please post the code fragment containing the registerDevice url you're changing

**Comment by Radiatorgaming420** [comment]
hey, im back again. I tried 2.1.6 and it still didnt work, after this post ill try 2.3.4 again (probably still wont work) but heres the code fragment where i have registerDevice in. Ill also link a few more screenshots.
![image](https://github.com/user-attachments/assets/5584fbb9-02e8-44b3-8fa2-7659fd6278ee)
![image](https://github.com/user-attachments/assets/bbb65e53-818b-4b98-b2b6-acb536de41ad)
![image](https://github.com/user-attachments/assets/d48a1aa1-7d17-42ff-9b6f-3321b7ba69c3) (gdata 1)
![image](https://github.com/user-attachments/assets/9d600fa7-6635-45d0-a4d8-e1fbd462ad0d) (gdata 2)

**Comment by ftde0** [comment]
https doesn't work on bare IPs. unless you've put up your instance on a domain and have a valid https certificate for that domain, it won't work.

swap out the registerDevice url to use http instead.

**Comment by Radiatorgaming420** [comment]
ok let me redo the apk then gimme a sec

**Comment by Radiatorgaming420** [comment]
alright yea, it worked, after changing https to http it did the trick, tysm ftde0
